import { ChatGoogleGenerativeAI } from "@langchain/google-genai";
import { ChatMistralAI } from "@langchain/mistralai";
import { AIMessage, HumanMessage, SystemMessage, tool, createAgent } from "langchain";
import * as z from "zod";
import { searchInternet } from "./internet.service.js";
import { sendEmail } from "./mail.service.js";

const geminiModel = new ChatGoogleGenerativeAI({
    model: "gemini-flash-latest",
    apiKey: process.env.GEMINI_API_KEY
});

const mistralModel = new ChatMistralAI({
    model: "mistral-small-latest",
    apiKey: process.env.MISTRAL_API_KEY
});

const searchInternetTool = tool(
    searchInternet,
    {
        name: "searchInternet",
        description: "Use this tool to get the latest information from the internet.",
        schema: z.object({
            query: z.string().describe("The search query to look up on the internet.")
        })
    }
);

const sendEmailTool = tool(
    async ({ to, subject, body }) => {
        try {
            await sendEmail({
                to,
                subject,
                text: body,
                html: `<div style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">${body.replace(/\n/g, '<br>')}</div>`
            });
            return JSON.stringify({ success: true, message: `Email successfully sent to ${to}` });
        } catch (error) {
            console.error("Tool Mail Error:", error);
            return JSON.stringify({ success: false, error: error.message });
        }
    },
    {
        name: "sendEmail",
        description: "Use this tool to send an email to a specific recipient. Use it only when the user explicitly requests to send an email.",
        schema: z.object({
            to: z.string().email().describe("The recipient's email address."),
            subject: z.string().describe("A concise and formal subject line for the email."),
            body: z.string().describe("The main content body text of the email generated by you.")
        })
    }
);

const agent = createAgent({
    model: mistralModel,
    tools: [ searchInternetTool, sendEmailTool ]
});

export async function generateResponse(messages) {
    console.log(messages)

    const response = await agent.invoke({
        messages: [
            new SystemMessage(`
                You are a helpful, smart and precise assistant for answering questions, researching data, and performing automated actions like sending emails.
                If you don't know the answer, say you don't know. 
                
                - If the question requires up-to-date information, use the "searchInternet" tool.
                - If the user asks you to send an email, compose a well-structured message body and trigger the "sendEmail" tool.
                - You can combine tools: if a user asks you to look something up and email it to them, first use "searchInternet", then use "sendEmail" with the compiled data.
            `),
            ...(messages.map(msg => {
                if (msg.role == "user") {
                    return new HumanMessage(msg.content)
                } else if (msg.role == "ai") {
                    return new AIMessage(msg.content)
                }
            })) ]
    });

    return response.messages[ response.messages.length - 1 ].text;
}

export const generateChatTitle = async (message) => {
    const response = await mistralModel.invoke([
        new SystemMessage(`You are a helpful assistant that generate concise and descriptive titles for chat conversations.
        User will provide you with the first message of a chat conversation, and you will generate a title that captures the essence of the conversation in 2-4 words. The title should be clear, relevant, and engaging.`),
        new HumanMessage(`Generate a title for a chat conversation based on the following first message: "${message}"`)
    ]);

    return response.text;
}